analyze_thread_memory_task:
  description: |
    CRITICAL: You are the Memory Analyzer. Your task is to analyze the feedback history for thread_id - {thread_id}.
    
    REQUIRED STEPS:
    1. Use essay_feedback_memory with this exact input:
       {tool_input}
       
    2. From the tool's output, look for these specific fields in each result:
       - 'memory': Contains the actual feedback content
       - 'metadata.timestamp': When the feedback was given
       
    3. For each memory entry found:
       - Extract the feedback content from the 'memory' field
       - Note the timestamp from 'metadata.timestamp'
       
    4. Analyze the collected feedback:
       - Organize chronologically using timestamps
       - Identify recurring themes across memory entries
       - Note progression in feedback over time
       - Identify areas consistently mentioned
    
    5. Prepare a summary that includes:
       - All unique pieces of feedback found
       - Common themes and patterns
       - Timeline of feedback progression
       - Areas needing continued focus

  expected_output: |
    MEMORY ANALYSIS:
    1. Feedback Timeline (newest to oldest):
       [List each piece of feedback with its timestamp]
    
    2. Key Themes Found:
       [Group similar feedback points]
    
    3. Progress Indicators:
       [Changes in feedback over time]
    
    4. Recurring Areas:
       [Topics mentioned multiple times]
    
    5. Recommendations:
       [How to build on existing feedback]

analyze_essay_task:
  description: |
    CRITICAL: You are the Essay Content Analyzer. Your task is to analyze the essay content for student with auth0_id - {auth0_id}.
    
    ESSAY DETAILS:
    - College: {college_name}
    - Prompt: {prompt}
    - Word Count: {word_count}
    - Essay Response: {essay_text}
    - Feedback Questions: {feedback_questions}
    
    Follow these steps:
    1. Essay Analysis:
       - Analyze the essay structure and flow
       - Evaluate content relevance and impact
       - Assess writing style and voice
       - Identify strengths and areas for improvement
       - Check alignment with prompt requirements
       - Ensure authenticity of student voice
       - Address specific feedback questions provided
    
    2. Output Format:
       - Provide clear, actionable feedback
       - Highlight specific examples from the essay
       - Suggest concrete improvements
       - Note any potential red flags or concerns
       - Maintain constructive tone throughout
       - Include responses to feedback questions

  expected_output: |
    ESSAY ANALYSIS:
    1. Structure and Flow:
       [Analysis of essay organization and transitions]
    
    2. Content and Relevance:
       [Evaluation of how well the essay addresses the prompt]
    
    3. Writing Style:
       [Assessment of voice, tone, and language use]
    
    4. Strengths:
       [List of effective elements]
    
    5. Areas for Improvement:
       [Specific suggestions with examples]
    
    6. Feedback Questions:
       [Direct responses to provided questions]

analyze_student_profile_task:
  description: |
    CRITICAL: You are the Student Profile Analyzer. Your task is to analyze the student profile to inform essay feedback.
    
    REQUIRED STEPS:
    1. Use StudentProfileTool with auth0_id - {auth0_id} to retrieve student data
    2. Focus on elements relevant to {college_name} essay analysis
    3. Connect profile insights to essay content and prompt: {prompt}
    
    ANALYSIS REQUIREMENTS:
    - Only analyze data that exists in the profile
    - DO NOT make assumptions about missing data
    - Focus on elements that could strengthen the essay
    - Consider how profile elements align with the college's values

  expected_output: |
    PROFILE ANALYSIS:
    1. Relevant Background Elements:
       [List elements that connect to essay]
    
    2. Key Experiences:
       [Experiences that could enhance essay]
    
    3. Theme Alignment:
       [How profile theme connects to essay]
    
    4. Missing Elements:
       [Note any relevant missing profile data]

analyze_college_data_task:
  description: |
    CRITICAL: You are the College Data Analyzer. Research and analyze essay requirements for {college_name}.
    
    RESEARCH FOCUS:
    - Essay requirements and guidelines
    - Word count requirements (current: {word_count})
    - Prompt-specific expectations: {prompt}
    - Writing style preferences
    - Common successful approaches
    
    Use the CollegeSearchTool to gather comprehensive information about {college_name}'s essay expectations.

  expected_output: |
    COLLEGE ANALYSIS:
    1. Essay Requirements:
       [Specific guidelines and expectations]
    
    2. Word Count Analysis:
       [Comparison with requirements]
    
    3. Style Preferences:
       [Writing style expectations]
    
    4. Success Patterns:
       [Common elements in successful essays]

research_college_preferences_task:
  description: |
    CRITICAL: You are the College Essay Researcher. Research successful essay approaches for {college_name}.
    
    RESEARCH REQUIREMENTS:
    - Use CollegeSearchTool to research {college_name}
    - Focus on prompt: {prompt}
    - Consider word count: {word_count}
    - Look for successful examples
    - Identify common pitfalls
    
    SEARCH GUIDELINES:
    1. Search for specific prompt patterns
    2. Research successful essay examples
    3. Find expert advice for this type of essay
    4. Identify common mistakes to avoid

  expected_output: |
    RESEARCH FINDINGS:
    1. Successful Patterns:
       [Common elements in successful essays]
    
    2. Expert Advice:
       [Recommendations from admissions experts]
    
    3. Common Pitfalls:
       [Mistakes to avoid]
    
    4. Specific Tips:
       [Advice for this prompt type]

generate_feedback_task:
  description: |
    CRITICAL: You are the Feedback Synthesizer. Create comprehensive feedback for the {college_name} essay.
    
    INPUTS TO CONSIDER:
    - College: {college_name}
    - Prompt: {prompt}
    - Word Count: {word_count}
    - Feedback Questions: {feedback_questions}
    
    SYNTHESIS REQUIREMENTS:
    1. Review the memory agent's analysis of previous feedback (if available)
    2. Build upon existing suggestions while avoiding repetition
    3. Address new aspects not covered in previous feedback
    4. Combine insights from all analyses
    5. Address specific feedback questions
    6. Provide actionable recommendations
    7. Maintain student's authentic voice
    8. Align with college preferences
    9. Consider word count constraints

  expected_output: |
    COMPREHENSIVE FEEDBACK:
    1. Overall Impression:
       [General assessment]
    
    2. Previous Feedback Context:
       [How this feedback builds on previous suggestions]
    
    3. Strengths:
       [Effective elements]
    
    4. Areas for Improvement:
       [Specific suggestions]
    
    5. Technical Aspects:
       [Structure, style, word count]
    
    6. Prompt Alignment:
       [How well essay addresses prompt]
    
    7. Specific Feedback:
       [Responses to feedback questions]
    
    8. Next Steps:
       [Prioritized action items]

