analyze_student_profile_task:
  description: |
    CRITICAL: You are the Profile Analyzer. Your task is to analyze the profile of student with auth0_id - {auth0_id} to identify potential essay topics.
    
    STEP 1: Profile Retrieval
    Use the StudentProfileTool with exact input:
    {{
        "auth0_id": "{auth0_id}"
    }}
    
    STEP 2: Analysis Focus
    Analyze the profile data focusing on:
    1. Academic achievements and interests that align with {college_name}'s values
    2. Extracurricular activities and leadership roles that demonstrate impact
    3. Personal background and unique experiences that could make compelling stories
    4. Key themes in their journey that connect to the essay prompt: {essay_prompt}
    5. Specific experiences that showcase their personality and values
    
    IMPORTANT:
    - Only analyze data that exists in the profile
    - Do not make assumptions about missing data
    - Focus on experiences that could address the prompt: {essay_prompt}
    - Note any unique elements that align with {college_name}'s values
    - Look for connections between their experiences and the essay topic
    
  expected_output: |
    A detailed analysis of the student's profile including:
    1. Key experiences and achievements that could address the prompt
    2. Unique personal qualities and background elements
    3. Specific examples of leadership, impact, or growth
    4. Themes that align with the college's values
    5. Potential story angles based on extracurriculars
    6. Notable awards or recognition relevant to the prompt
    7. Family background context if relevant
    8. Academic interests and passions that could tie in
    Format as a structured list with clear sections and bullet points.

check_ideas_history_task:
  description: |
    CRITICAL: You are the Ideas History Checker. Your task is to analyze previous brainstorming ideas for this essay.
    
    STEP 1: History Retrieval
    Use the IdeasHistoryTool with exact input:
    {{
        "auth0_id": "{auth0_id}",
        "thread_id": "{thread_id}"
    }}
    
    STEP 2: Analysis Focus
    Analyze the history to:
    1. Retrieve all past essay ideas for {college_name}
    2. Analyze patterns and themes related to {essay_prompt}
    3. Identify successful approaches that worked well
    4. Note ideas to avoid repeating
    
    IMPORTANT:
    - Look for themes that resonated with {college_name}'s values
    - Identify any gaps in addressing {essay_prompt}
    - Note which approaches were most successful
    - Ensure new ideas build on past successes
    
  expected_output: |
    A comprehensive analysis of brainstorming history including:
    1. Summary of previous ideas for this college/prompt
    2. Themes that resonated well in past sessions
    3. Approaches or angles to avoid repeating
    4. Opportunities to build on successful past themes
    5. Evolution of brainstorming approaches used
    6. Context for why certain ideas worked well
    7. Gaps or areas not yet explored
    8. Recommendations for fresh perspectives
    Format as a structured report with clear sections.

research_college_values_task:
  description: |
    CRITICAL: You are the College Values Researcher. Research what {college_name} values in their applicants.
    
    STEP 1: Research Execution
    Use the CollegeSearchTool with exact input:
    {{
        "college_name": "{college_name}",
        "query": "What does {college_name} value in essays about {essay_prompt}"
    }}
    
    STEP 2: Research Focus
    Analyze the results focusing on:
    1. {college_name}'s mission and values
    2. Qualities they seek in essays
    3. Their culture and community
    4. Successful essay examples
    5. Unique aspects they value in personal stories
    
    IMPORTANT:
    - Focus on values relevant to {essay_prompt}
    - Look for recent admissions trends at {college_name}
    - Identify unique aspects of their essay evaluation
    - Find specific examples of successful essays
    
  expected_output: |
    A detailed analysis of college values including:
    1. Core values and mission statement highlights
    2. Specific qualities they seek in essays
    3. Recent admissions trends and preferences
    4. Unique aspects of college culture
    5. Examples of values in action
    6. Key themes from successful essays
    7. Specific guidelines or preferences
    8. Red flags or approaches to avoid
    Format as a structured report with clear sections and examples.

research_essay_examples_task:
  description: |
    CRITICAL: You are the Essay Examples Researcher. Research successful essays for {college_name}.
    
    STEP 1: Research Execution
    Use the CollegeSearchTool with exact input:
    {{
        "college_name": "{college_name}",
        "query": "successful {college_name} essays {essay_prompt} examples"
    }}
    
    STEP 2: Research Focus
    Analyze the results focusing on:
    1. Essays that got students into {college_name}
    2. Approaches that worked for similar prompts
    3. Unique angles that stood out
    4. Expert advice for {essay_prompt}
    
    IMPORTANT:
    - Focus on essays that got students admitted to {college_name}
    - Look for creative approaches to {essay_prompt}
    - Note common pitfalls to avoid
    - Find expert tips specific to this type of prompt
    
  expected_output: |
    A comprehensive analysis of successful essays including:
    1. Key patterns from successful submissions
    2. Unique approaches that worked well
    3. Common themes and structures used
    4. Creative angles that stood out
    5. Expert advice for this prompt type
    6. Common pitfalls to avoid
    7. Specific examples of effective hooks
    8. Writing techniques that resonated
    Format as a structured guide with clear sections and examples.

generate_essay_ideas_task:
  description: |
    CRITICAL: You are the Ideas Generator. Generate exactly 5 unique essay ideas.
    
    STEP 1: Input Analysis
    Consider all available data:
    - Student profile (auth0_id: {auth0_id})
    - College preferences ({college_name})
    - Essay prompt: {essay_prompt}
    - Previous ideas (thread_id: {thread_id})
    
    STEP 2: Idea Generation Process
    For each idea:
    1. First draft the complete idea with all components
    2. Then distill it to its core essence
    3. Finally output ONLY the distilled version in ≤250 characters
    
    IMPORTANT:
    - Generate EXACTLY 5 ideas
    - Each idea MUST be under 250 characters
    - Ideas must be specific to the student's experiences
    - Ideas must connect to {college_name}'s values
    - Ideas must directly address {essay_prompt}
    - Avoid any ideas found in thread history
    
  expected_output: |
    5 ESSAY IDEAS (each ≤250 characters):
    1. [First idea in 250 chars or less]
    2. [Second idea in 250 chars or less]
    3. [Third idea in 250 chars or less]
    4. [Fourth idea in 250 chars or less]
    5. [Fifth idea in 250 chars or less]

    DO NOT include any additional details, rationales, or formatting.
    Output ONLY the numbered ideas, each under 250 characters. 