read_cv_task:
  description: >
    Analyze the student profile using the Auth0 ID to find their target college list using the tools you have access to:

    Auth0 ID of the student: {auth0_id}
  expected_output: >
    A comprehensive analysis of the student's target colleges to generate a list of colleges that the student is interested in applying to.

analyze_student_profile_task:
  description: |
    CRITICAL: You are the Student Profile Analyzer. Your task is to analyze the student profile with auth0_id - {auth0_id} using ONLY data from the StudentProfileMemoryTool.
    
    1. Use StudentProfileMemoryTool with input {"auth0_id": "{auth0_id}"} to retrieve:
       - student_statistics (GPA, SAT scores, etc.)
       - student_preferences (college types, campus sizes, etc.)
       - student_basic_info (name, email, etc.)
       - student_context (background information)
       - student_theme
       - hooks
       - personality_type
       - target_colleges
       - extracurriculars
       - awards
    
    2. Data Verification:
       - Verify all required fields are present
       - Check data completeness and validity
       - Note any missing or incomplete information
    
    3. Analysis Process:
       - Review target colleges list
       - Analyze academic statistics and achievements
       - Evaluate student preferences and background
       - Assess extracurricular activities and awards
       - Consider personality traits and hooks
    
    4. Output Format:
       - Provide analysis ONLY based on available data
       - DO NOT make assumptions about missing data
       - Clearly indicate any missing information
       - Transfer the analyzed profile data to other agents

  expected_output: |
    ANALYSIS:
    1. Target Colleges:
       - List of colleges found in profile
       - Any specific college preferences noted

    2. Academic Profile:
       - GPA and Test Scores
       - Class Rank
       - Major Preferences

    3. Student Background:
       - Demographic Information
       - Context and Background
       - Financial Considerations

    4. Activities and Achievements:
       - Current Extracurriculars
       - Awards and Recognition
       - Leadership Positions

    5. Personal Characteristics:
       - Theme/Hooks
       - Personality Type
       - Special Circumstances

    6. Missing Fields:
       - List any critical fields not found in database

check_past_suggestions_task:
  description: |
    CRITICAL: You are the Past EC Suggestions Analyst. Your task is to review all previously suggested activities for auth0_id - {auth0_id} and activity_type - {activity_type} using the PastSuggestionsHistoryTool.
    
    1. Use PastSuggestionsHistoryTool to get complete history:
       - Command: Use tool with auth0_id - {auth0_id} and activity_type - {activity_type}
       - Retrieve all past EC suggestions
       - If no previous suggestions exist, note this explicitly
    
    2. If suggestions exist:
       - Create comprehensive list of past suggestions
       - Identify key themes and areas already covered
       - Create a detailed exclusion list that includes:
         * Exact activity names to avoid
         * Similar roles or positions (e.g., if "Math Tutor" exists, avoid "Science Tutor" or "Academic Tutor")
         * Related subject areas (e.g., if "Historical Research" exists, avoid other historical research activities)
         * Similar organizational roles (e.g., if "Club President" exists, avoid "Club Leader" in same domain)
    
    3. Output Format:
       - List all previously suggested activities
       - Group similar activities by theme
       - Provide specific guidance on what types of activities to avoid
       - Create clear boundaries for new suggestions

  expected_output: |
    PAST SUGGESTIONS ANALYSIS:
    1. Previously Suggested Activities:
       - Complete list of past suggestions
       - OR "No previous suggestions found"

    2. Theme Analysis:
       - Key themes already covered
       - Similar roles to avoid
       - Subject areas to exclude

    3. Exclusion Guidelines:
       - Specific activities to avoid
       - Related roles to exclude
       - Similar themes to skip

scout_activities_task:
  description: |
    CRITICAL: You are the EC Research Specialist. Your task is to research successful extracurricular activities for the student's target colleges using the SearchTool.
    
    1. For each target college (from cv_reader):
       - Use SearchTool to search:
         * "ec that got students into [college name]"
         * "ec that worked for [college name]"
         * Activities aligned with college's values
    
    2. Research Process:
       - Focus on activities matching student's profile
       - Look for high-impact opportunities
       - Find leadership positions
       - Consider activities that complement student's theme
    
    3. Output Format:
       - List successful activities by college
       - Include activity types and impact levels
       - Note any patterns across colleges

  expected_output: |
    ACTIVITY RESEARCH RESULTS:
    1. By Target College:
       - College Name:
         * Successful Activities List
         * Notable Patterns
         * Impact Levels

    2. Overall Patterns:
       - Common successful activities
       - High-impact opportunities
       - Leadership positions

generate_recommendations_task:
  description: |
    CRITICAL: You are the EC Strategy Developer. Your task is to generate 5 COMPLETELY UNIQUE and impactful EC recommendations based on all previous analyses.
    
    IMPORTANT CONSTRAINTS:
    - Activity Type: {activity_type}
    - Hours per Week: {hrs_per_wk}
    
    UNIQUENESS REQUIREMENTS:
    1. Check Past Activities:
       - Review past_ec_suggestion_checker's exclusion list thoroughly
       - DO NOT suggest anything similar to past activities
       - Avoid activities with similar:
         * Roles/positions (e.g., if "Math Tutor" exists, don't suggest "Science Tutor")
         * Subject areas (e.g., if "Historical Research" exists, find completely different domain)
         * Organizational roles (e.g., if "Club President" exists, find non-leadership roles)
    
    2. Ensure True Uniqueness:
       - Each suggestion must be fundamentally different from past suggestions
       - Different skill sets and domains
       - Different types of responsibilities
       - Different organizational contexts
    
    3. Generate 5 Unique Recommendations:
       Each recommendation must:
       - Be completely distinct from past suggestions
       - Match the specified activity type: {activity_type}
       - Require approximately {hrs_per_wk} hours per week
       - Include Position/Leadership Name (MAX 50 CHARACTERS)
       - Include Activity Description (MAX 200 CHARACTERS)
    
    4. Verification Steps:
       - Cross-reference with past suggestions to ensure no overlap
       - Verify each suggestion explores a new domain or approach
       - Ensure activities are realistic and achievable
       - Check character limits are respected
       - Validate time commitment matches {hrs_per_wk} hours/week
       - Confirm activity type matches {activity_type}

  expected_output: |
    NEW UNIQUE RECOMMENDATIONS:
    1. Activity Name | {activity_type}
       Hours per Week: {hrs_per_wk}
       Position: [Leadership Title - max 50 chars]
       Description: [Activity Details - max 200 chars]

    2. Activity Name | {activity_type}
       Hours per Week: {hrs_per_wk}
       Position: [Leadership Title - max 50 chars]
       Description: [Activity Details - max 200 chars]

    3. Activity Name | {activity_type}
       Hours per Week: {hrs_per_wk}
       Position: [Leadership Title - max 50 chars]
       Description: [Activity Details - max 200 chars]

    4. Activity Name | {activity_type}
       Hours per Week: {hrs_per_wk}
       Position: [Leadership Title - max 50 chars]
       Description: [Activity Details - max 200 chars]

    5. Activity Name | {activity_type}
       Hours per Week: {hrs_per_wk}
       Position: [Leadership Title - max 50 chars]
       Description: [Activity Details - max 200 chars]


 
